# *Code Flow*

1. Load the dataset
2. Basic Programming
3. Training Process
    - Create the Model
    - Forward Pass
    - Loss Calculation
    - Backward Pass
    - Parameters Update
4. Model evaluation

In [3]:
## import some all necessary module
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(4)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
296    891936         B       10.910         12.35           69.14      363.7   
274   8911163         M       17.930         24.48          115.20      998.9   
17   84862001         M       16.130         20.68          108.10      798.8   
66     859464         B        9.465         21.01           60.11      269.4   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
296          0.08518           0.04721         0.01236              0.01369   
274          0.08855           0.07027         0.05699              0.04744   
17           0.11700           0.20220         0.17220              0.10280   
66           0.10440           0.07773         0.02172              0.01504   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
296  ...          14.82            72.42       392.2           0.09312   
274  ...          34.69           135.10      1320.0           0.13150   
17   ...          31.48           136.80      1315.0           0.17890   
66   ...          31.56            67.03       330.7           0.15480   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
296            0.07506          0.02884               0.03194          0.2143   
274            0.18060          0.20800               0.11360          0.2504   
17             0.42330          0.47840               0.20730          0.3706   
66             0.16640          0.09412               0.06517          0.2878   

     fractal_dimension_worst  Unnamed: 32  
296                  0.06643          NaN  
274                  0.07948          NaN  
17                   0.11420          NaN  
66                   0.09211          NaN  

[4 rows x 33 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.sample(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
241         B        12.42         15.04           78.61      476.5   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
241          0.07926           0.03393         0.01053              0.01108   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
241         0.1546  ...          13.2          20.37            83.85   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
241       543.4            0.1037            0.07776          0.06243   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
241               0.04052          0.2901                  0.06783  

[1 rows x 31 columns]

In [7]:
df.shape

(569, 31)

In [8]:
X = df.iloc[:, 1:]
X.head(2)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [9]:
y = df.iloc[:, 0]
y.head(1)

0    M
Name: diagnosis, dtype: object

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## *Scaling*

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [13]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

#### All varivable are numpy array to need to transform to Tensor because we build the model into the PyTorch

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_test_tensor

tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]],
       dtype=torch.float64)

## *Convert float64 to float32 format Because i use `nn.Linear`*

In [16]:
X_train_tensor = X_train_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)


In [17]:
X_test_tensor = X_test_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

## Use dataloader class

In [29]:
from torch.utils.data import DataLoader, Dataset

In [30]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):   ## if you want to apply any transformation then apply in this function like aug, lama, or any
        return self.features[index], self.labels[index]

In [31]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [32]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# *Defining The Model*

In [33]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.liner = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.liner(features)
        y_pred = self.sigmoid(out)
        return y_pred
    
    def loss_function(self, y_pred, y):
        ## Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        ## calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameter

In [41]:
learning_rate = 0.001
epochs = 300


# *Training Pipeline*

In [42]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

## define the loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
        y_pred = model(batch_features)
        loss = loss_function(y_pred, batch_labels.view(-1, 1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")
        

Epoch: 1, Loss: 0.6150254011154175
Epoch: 2, Loss: 0.6664461493492126
Epoch: 3, Loss: 0.6878558397293091
Epoch: 4, Loss: 0.6405863165855408
Epoch: 5, Loss: 0.6682294607162476
Epoch: 6, Loss: 0.6941766142845154
Epoch: 7, Loss: 0.7058642506599426
Epoch: 8, Loss: 0.7068745493888855
Epoch: 9, Loss: 0.6224711537361145
Epoch: 10, Loss: 0.6819227933883667
Epoch: 11, Loss: 0.647877037525177
Epoch: 12, Loss: 0.6238049268722534
Epoch: 13, Loss: 0.6384750008583069
Epoch: 14, Loss: 0.7516382932662964
Epoch: 15, Loss: 0.7815454602241516
Epoch: 16, Loss: 0.6182927489280701
Epoch: 17, Loss: 0.644776463508606
Epoch: 18, Loss: 0.7231646776199341
Epoch: 19, Loss: 0.6661175489425659
Epoch: 20, Loss: 0.6741623282432556
Epoch: 21, Loss: 0.6669051051139832
Epoch: 22, Loss: 0.6965373754501343
Epoch: 23, Loss: 0.6751796007156372
Epoch: 24, Loss: 0.6079309582710266
Epoch: 25, Loss: 0.6942059397697449
Epoch: 26, Loss: 0.6184678077697754
Epoch: 27, Loss: 0.5880733728408813
Epoch: 28, Loss: 0.6319859623908997
Epo

In [43]:
model.liner.weight

Parameter containing:
tensor([[ 0.1504, -0.0405, -0.0228,  0.0833,  0.0306,  0.0651,  0.0988, -0.1743,
          0.1340, -0.1230,  0.1716, -0.0527, -0.1002, -0.1812, -0.1040,  0.0500,
         -0.1207, -0.0579,  0.1641, -0.0326,  0.0199,  0.1657, -0.1624, -0.0382,
          0.1473, -0.1498,  0.0160,  0.0912,  0.0090, -0.0595]],
       requires_grad=True)

## *Model evaluation*

In [22]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.6228070259094238


## ***Use build in Loss function and Optimizer***

In [23]:
## import loss function
loss_function = nn.BCELoss()

In [24]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.liner = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.liner(features)
        y_pred = self.sigmoid(out)
        return y_pred
    
    

In [25]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model(X_train_tensor)
    

    ## loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    # print(loss)

    ## backward pass
    loss.backward()

    ## update the weight
    with torch.no_grad():
        model.liner.weight -= learning_rate * model.liner.weight.grad
        model.liner.bias -= learning_rate * model.liner.bias.grad
    
    ## zero gradients because next epo not effect the previous grad value
    model.liner.weight.grad.zero_()
    model.liner.bias.grad.zero_()
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.791978120803833
Epoch 2, Loss: 0.5909687280654907
Epoch 3, Loss: 0.4861624538898468
Epoch 4, Loss: 0.4227188229560852
Epoch 5, Loss: 0.37966522574424744
Epoch 6, Loss: 0.3481641113758087
Epoch 7, Loss: 0.32387834787368774
Epoch 8, Loss: 0.3044265806674957
Epoch 9, Loss: 0.2883893549442291
Epoch 10, Loss: 0.2748658359050751
Epoch 11, Loss: 0.2632555067539215
Epoch 12, Loss: 0.2531414031982422
Epoch 13, Loss: 0.2442244589328766
Epoch 14, Loss: 0.23628392815589905
Epoch 15, Loss: 0.22915279865264893
Epoch 16, Loss: 0.22270220518112183
Epoch 17, Loss: 0.216830775141716
Epoch 18, Loss: 0.21145747601985931
Epoch 19, Loss: 0.20651647448539734
Epoch 20, Loss: 0.20195385813713074
Epoch 21, Loss: 0.19772467017173767
Epoch 22, Loss: 0.19379118084907532
Epoch 23, Loss: 0.19012142717838287
Epoch 24, Loss: 0.1866881251335144
Epoch 25, Loss: 0.18346768617630005
Epoch 26, Loss: 0.18043971061706543
Epoch 27, Loss: 0.1775864213705063
Epoch 28, Loss: 0.1748921424150467
Epoch 29, Loss: 0.

In [26]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5301631093025208


## *Import torch optim SDG, Adam and build most efficient model*

In [27]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model(X_train_tensor)
    

    ## loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    # print(loss)

    ## backward pass
    loss.backward()

    ## update the weight
    optimizer.step()
    # with torch.no_grad():
    #     model.liner.weight -= learning_rate * model.liner.weight.grad
    #     model.liner.bias -= learning_rate * model.liner.bias.grad
    
    ## zero gradients because next epo not effect the previous grad value
    optimizer.zero_grad()
    # model.liner.weight.grad.zero_()
    # model.liner.bias.grad.zero_()
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.8084181547164917
Epoch 2, Loss: 0.37578901648521423
Epoch 3, Loss: 0.25601840019226074
Epoch 4, Loss: 0.19908127188682556
Epoch 5, Loss: 0.16072587668895721
Epoch 6, Loss: 0.1327405869960785
Epoch 7, Loss: 0.11390195786952972
Epoch 8, Loss: 0.10268490761518478
Epoch 9, Loss: 0.09584258496761322
Epoch 10, Loss: 0.09137768298387527
Epoch 11, Loss: 0.08831267058849335
Epoch 12, Loss: 0.08609438687562943
Epoch 13, Loss: 0.08437719941139221
Epoch 14, Loss: 0.08293574303388596
Epoch 15, Loss: 0.0816231295466423
Epoch 16, Loss: 0.0803486630320549
Epoch 17, Loss: 0.07906487584114075
Epoch 18, Loss: 0.0777583196759224
Epoch 19, Loss: 0.07644206285476685
Epoch 20, Loss: 0.07514824718236923
Epoch 21, Loss: 0.0739198848605156
Epoch 22, Loss: 0.07280074059963226
Epoch 23, Loss: 0.07182398438453674
Epoch 24, Loss: 0.07100316882133484
Epoch 25, Loss: 0.07033023983240128
Epoch 26, Loss: 0.06978132575750351
Epoch 27, Loss: 0.06932545453310013
Epoch 28, Loss: 0.06893189251422882
Epoch 2

# ***Most clean Code***

In [44]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

## define the loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
        y_pred = model(batch_features)
        loss = loss_function(y_pred, batch_labels.view(-1, 1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.47322216629981995
Epoch: 2, Loss: 0.5524964332580566
Epoch: 3, Loss: 0.549140989780426
Epoch: 4, Loss: 0.39925211668014526
Epoch: 5, Loss: 0.3441312909126282
Epoch: 6, Loss: 0.22156013548374176
Epoch: 7, Loss: 0.18181200325489044
Epoch: 8, Loss: 0.3314932882785797
Epoch: 9, Loss: 0.3048730790615082
Epoch: 10, Loss: 0.3815922737121582
Epoch: 11, Loss: 0.20153197646141052
Epoch: 12, Loss: 0.2906620502471924
Epoch: 13, Loss: 0.3240034878253937
Epoch: 14, Loss: 0.12241649627685547
Epoch: 15, Loss: 0.24885079264640808
Epoch: 16, Loss: 0.3374103903770447
Epoch: 17, Loss: 0.4919983446598053
Epoch: 18, Loss: 0.1403505504131317
Epoch: 19, Loss: 0.18560507893562317
Epoch: 20, Loss: 0.27426132559776306
Epoch: 21, Loss: 0.3685479462146759
Epoch: 22, Loss: 0.12069334834814072
Epoch: 23, Loss: 0.16045139729976654
Epoch: 24, Loss: 0.13125978410243988
Epoch: 25, Loss: 0.09361529350280762
Epoch: 26, Loss: 0.21166189014911652
Epoch: 27, Loss: 0.16033601760864258
Epoch: 28, Loss: 0.1381

In [45]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9844
