## ***Most efficiently Handel data using PyTorch Dataset and Dataloader class***

In [26]:
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

## **BUild toy dataset**

In [12]:
from sklearn.datasets import make_classification
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2, 
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [13]:
X.shape

(10, 2)

In [14]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [15]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [18]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [7]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

## ***Now time to create Our custom Dataset and dataloader class***

In [ ]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):   ## if you want to apply any transformation then apply in this function like aug, lama, or any
        return self.features[index], self.labels[index]
    

In [20]:
dataset = CustomDataset(X, y)

In [24]:
len(dataset)

10

In [ ]:
dataset[1]

(tensor([-1.1402, -0.8388]), tensor(0))

## **Dataloader parameter**
- batch-size
- shuffle
- num_workers
- pin-memory : its indicate the GPU
- collate_fn: its custom function like what ever i want to update in custom then we use this function
- sampler
-drop_last

In [ ]:
dataloader = DataLoader(dataset=dataset, batch_size=2, shuffle=True)

In [36]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_"*30)

tensor([[ 1.7774,  1.5116],
        [-0.9382, -0.5430]])
tensor([1, 1])
______________________________
tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]])
tensor([0, 0])
______________________________
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
______________________________
tensor([[-1.1402, -0.8388],
        [-0.5872, -1.9717]])
tensor([0, 0])
______________________________
tensor([[ 1.7273, -1.1858],
        [ 1.8997,  0.8344]])
tensor([1, 1])
______________________________
