In [2]:
import numpy as np

In [3]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [4]:
# zip Function

In [5]:
ziped = zip(y_predicted, y_true)

for a, b in ziped:
    print(a, b)

1 0.3
1 0.7
0 1.0
0 0.0
1 0.5


In [6]:
def mea(y_true, y_prdicted):
    total_error = 0
    for yt, yp in zip(y_true, y_prdicted):
        total_error += abs(yt - yp)
    print('Total error: ', total_error)
    mea = total_error / len(y_true)
    print("MAE: ", mea)
    return mea

In [7]:
mea(y_true, y_predicted)

Total error:  2.5
MAE:  0.5


0.5

In [8]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [9]:
np.log([0])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1384\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
np.log([.0000000000000000000000000000000000001])

array([-85.19564844])

# Log Loss Function Implementation

In [12]:
eplison = 1e-15
eplison

1e-15

In [20]:
y_predicted

array([1, 1, 0, 0, 1])

In [21]:
y_predicted_new = [max(i, eplison) for i in y_predicted]

In [22]:
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [23]:
y_predicted_new = [min(i, 1 - eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

## Numpy Array Approch

In [25]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [26]:
def logLoss(y_true, y_predicted):
    eplison = 1e-15
    y_predicted_new = [max(i, eplison) for i in y_predicted]
    y_predicted_new = [min(i, eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [27]:
logLoss(y_true, y_predicted)

17.269388197455342