## Play With Tensor

In [1]:
import torch
print(torch.__version__)

2.3.1+cu118


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Sorry sir please buy a RTX4090 And Run this code one more time!")

GPU is available!
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


## Creating a Tensor

In [4]:
a = torch.empty(2, 3) ## empty function just assign free memory in location do not store any number its print there gurbage number.
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
type(a)

torch.Tensor

In [6]:
## Zero tensor
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
## one tensor
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
## random tensor
torch.rand(2, 3)

tensor([[0.5350, 0.9960, 0.9195],
        [0.3175, 0.0782, 0.8979]])

In [10]:
## use manual seed ot make sure always produce the same number
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
## build a custom Tensor
torch.tensor(
    [
        [1, 2, 3],
        [3, 4, 5],
        [1, 6, 7]
    ]
)

tensor([[1, 2, 3],
        [3, 4, 5],
        [1, 6, 7]])

In [ ]:
## Use arange, linspace, eye, full function to create custom tensor

print("Use arange function: ", torch.arange(0, 10, 2))

## use linspace
print(f"Use linspace: {torch.linspace(0, 10 , 10)}")

##use eye method its a identity metrix
print(f"Use eye method: {torch.eye(5)}")

# use full method
print(f"Use full method: {torch.full((3, 3), 5)}")

Use arange function:  tensor([0, 2, 4, 6, 8])
Use linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Use eye method: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Use full method: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shape

In [33]:
x = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

In [19]:
x.shape

torch.Size([2, 3])

*In tensor has a function is `like` which you can use to create a tensor like another tensor shape like*

In [20]:
## Example of to create a empty tensor like another tensor
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
## like zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
## one like
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
## random value tensor
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Type

In [23]:
x.dtype

torch.int64

In [24]:
## Assign the data type on tensor creation time
torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ], dtype=torch.int32
)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [25]:
## another example
torch.tensor(
    [1, 2, 3], dtype=torch.float16
)

tensor([1., 2., 3.], dtype=torch.float16)

## Transfer one data type to user data type then use `.to` operator

In [26]:
x.dtype

torch.int64

In [30]:
x= x.to(torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
x.dtype

torch.float32

## Apply Mathematical operations in tensor

In [36]:
## scaler
x = torch.rand(2, 2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [37]:
## addition
x+2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [38]:
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [39]:
x*3

tensor([[0.6717, 0.9070],
        [0.5353, 2.4715]])

In [40]:
(x*100) // 3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [41]:
## power 
x**8

tensor([[6.3144e-06, 6.9829e-05],
        [1.0269e-06, 2.1221e-01]])

In [42]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [43]:
## same dim tensor mathematical operations
a + b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [44]:
a * b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [45]:
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [47]:
## to get absulate value of the tensor
c = torch.tensor(
    [1, 2, -4, -5, 3]
)

In [48]:
torch.abs(c)

tensor([1, 2, 4, 5, 3])

In [49]:
## to get negative then use 'neg' function
torch.neg(c)

tensor([-1, -2,  4,  5, -3])

In [50]:
## use round, cell, floor, clamp function on the tensor
d = torch.tensor(
    [1.5, 0.4, 3.7, 9, 0.4]
)

In [51]:
torch.ceil(d)

tensor([2., 1., 4., 9., 1.])

In [52]:
torch.round(d)

tensor([2., 0., 4., 9., 0.])

In [53]:
torch.floor(d)

tensor([1., 0., 3., 9., 0.])

In [55]:
torch.clamp(d, min=4, max=6)

tensor([4., 4., 4., 6., 4.])