## Play With Tensor

In [1]:
import torch
print(torch.__version__)

2.3.1+cu118


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Sorry sir please buy a RTX4090 And Run this code one more time!")

GPU is available!
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


## Creating a Tensor

In [4]:
a = torch.empty(2, 3) ## empty function just assign free memory in location do not store any number its print there gurbage number.
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
type(a)

torch.Tensor

In [6]:
## Zero tensor
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
## one tensor
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
## random tensor
torch.rand(2, 3)

tensor([[0.5350, 0.9960, 0.9195],
        [0.3175, 0.0782, 0.8979]])

In [10]:
## use manual seed ot make sure always produce the same number
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
## build a custom Tensor
torch.tensor(
    [
        [1, 2, 3],
        [3, 4, 5],
        [1, 6, 7]
    ]
)

tensor([[1, 2, 3],
        [3, 4, 5],
        [1, 6, 7]])

In [ ]:
## Use arange, linspace, eye, full function to create custom tensor

print("Use arange function: ", torch.arange(0, 10, 2))

## use linspace
print(f"Use linspace: {torch.linspace(0, 10 , 10)}")

##use eye method its a identity metrix
print(f"Use eye method: {torch.eye(5)}")

# use full method
print(f"Use full method: {torch.full((3, 3), 5)}")

Use arange function:  tensor([0, 2, 4, 6, 8])
Use linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Use eye method: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Use full method: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shape

In [33]:
x = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

In [19]:
x.shape

torch.Size([2, 3])

*In tensor has a function is `like` which you can use to create a tensor like another tensor shape like*

In [20]:
## Example of to create a empty tensor like another tensor
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
## like zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
## one like
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [35]:
## random value tensor
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Type

In [23]:
x.dtype

torch.int64

In [24]:
## Assign the data type on tensor creation time
torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ], dtype=torch.int32
)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [25]:
## another example
torch.tensor(
    [1, 2, 3], dtype=torch.float16
)

tensor([1., 2., 3.], dtype=torch.float16)

## Transfer one data type to user data type then use `.to` operator

In [26]:
x.dtype

torch.int64

In [30]:
x= x.to(torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
x.dtype

torch.float32

## Apply Mathematical operations in tensor

In [36]:
## scaler
x = torch.rand(2, 2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [37]:
## addition
x+2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [38]:
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [39]:
x*3

tensor([[0.6717, 0.9070],
        [0.5353, 2.4715]])

In [40]:
(x*100) // 3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [41]:
## power 
x**8

tensor([[6.3144e-06, 6.9829e-05],
        [1.0269e-06, 2.1221e-01]])

In [42]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [43]:
## same dim tensor mathematical operations
a + b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [44]:
a * b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [45]:
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [47]:
## to get absulate value of the tensor
c = torch.tensor(
    [1, 2, -4, -5, 3]
)

In [48]:
torch.abs(c)

tensor([1, 2, 4, 5, 3])

In [49]:
## to get negative then use 'neg' function
torch.neg(c)

tensor([-1, -2,  4,  5, -3])

In [50]:
## use round, cell, floor, clamp function on the tensor
d = torch.tensor(
    [1.5, 0.4, 3.7, 9, 0.4]
)

In [51]:
torch.ceil(d)

tensor([2., 1., 4., 9., 1.])

In [52]:
torch.round(d)

tensor([2., 0., 4., 9., 0.])

In [53]:
torch.floor(d)

tensor([1., 0., 3., 9., 0.])

In [55]:
torch.clamp(d, min=4, max=6)

tensor([4., 4., 4., 6., 4.])

In [70]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)

In [65]:
e

tensor([[5, 7, 5],
        [9, 9, 7]])

In [67]:
torch.sum(e)

tensor(42)

In [68]:
## sum along column
torch.sum(e, dim=0)

tensor([14, 16, 12])

In [69]:
## sum along rows
torch.sum(e, dim=1)

tensor([17, 25])

In [72]:
## mean
torch.mean(e, dim=0)

tensor([7.0000, 8.0000, 8.5000])

In [74]:
torch.median(e)

tensor(8.)

In [75]:
torch.max(e), torch.min(e), torch.std(e), torch.var(e)

(tensor(9.), tensor(5.), tensor(1.6021), tensor(2.5667))

In [77]:
torch.argmax(e) ## its talk about the largest element position

tensor(1)

In [78]:
torch.argmin(e)

tensor(0)

## Matrix Operation

In [80]:
f = torch.randint(size=(3, 3), high=10, low=1, dtype=torch.float32)
g = torch.randint(size=(3, 3), high=10, low=1, dtype=torch.float32)

print(f)
print(g)

tensor([[1., 3., 1.],
        [1., 1., 2.],
        [7., 4., 3.]])
tensor([[6., 3., 9.],
        [4., 6., 7.],
        [4., 7., 7.]])


In [81]:
## matrix multiplication
torch.matmul(f, g)

tensor([[ 22.,  28.,  37.],
        [ 18.,  23.,  30.],
        [ 70.,  66., 112.]])

In [82]:
## dot products
vector1 = torch.tensor(
    [1, 2]
)
vector2 = torch.tensor(
    [3, 4]
)

In [83]:
torch.dot(vector1, vector2)

tensor(11)

In [84]:
f

tensor([[1., 3., 1.],
        [1., 1., 2.],
        [7., 4., 3.]])

In [85]:
torch.transpose(f, 0, 1)

tensor([[1., 1., 7.],
        [3., 1., 4.],
        [1., 2., 3.]])

In [87]:
## to get the determinate
torch.det(g)

tensor(-6.0000)

## Comparison operations

In [88]:
i = torch.randint(size=(2, 3), low=4, high=15, dtype=torch.float32)
j = torch.randint(size=(2, 3), low=4, high=15, dtype=torch.float32)

print(i)
print(j)

tensor([[12., 14.,  9.],
        [14., 12.,  8.]])
tensor([[ 8., 14., 14.],
        [ 4.,  9., 11.]])


In [89]:
i > j

tensor([[ True, False, False],
        [ True,  True, False]])

In [90]:
i < j

tensor([[False, False,  True],
        [False, False,  True]])

In [91]:
i == j

tensor([[False,  True, False],
        [False, False, False]])

In [92]:
i >= j

tensor([[ True,  True, False],
        [ True,  True, False]])

In [93]:
i <= j

tensor([[False,  True,  True],
        [False, False,  True]])

## Spatial Function

In [94]:
k = torch.randint(size=(2, 3), high=15, low=4, dtype=torch.float32)
k

tensor([[12.,  7.,  6.],
        [14.,  4.,  9.]])

In [95]:
## log
torch.log(k)

tensor([[2.4849, 1.9459, 1.7918],
        [2.6391, 1.3863, 2.1972]])

In [96]:
torch.exp(k)

tensor([[1.6275e+05, 1.0966e+03, 4.0343e+02],
        [1.2026e+06, 5.4598e+01, 8.1031e+03]])

In [97]:
torch.sigmoid(k)

tensor([[1.0000, 0.9991, 0.9975],
        [1.0000, 0.9820, 0.9999]])

In [98]:
torch.softmax(k, dim=1)

tensor([[9.9087e-01, 6.6764e-03, 2.4561e-03],
        [9.9326e-01, 4.5094e-05, 6.6925e-03]])

In [99]:
torch.relu(k)

tensor([[12.,  7.,  6.],
        [14.,  4.,  9.]])

## Inplace Operation

In [100]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])


*Inplace is operation like add a value and store this value in existing memory address not take extra new memory*

In [101]:
m.add_(n)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [102]:
m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [103]:
n

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [104]:
## use in activation function
torch.relu(m) ## its take extra memory space

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [107]:
m.sigmoid_()

tensor([[0.7103, 0.7959, 0.8426],
        [0.8279, 0.6396, 0.8073]])

In [108]:
m

tensor([[0.7103, 0.7959, 0.8426],
        [0.8279, 0.6396, 0.8073]])

## Coping the tensor

In [110]:
a = torch.randint(size=(3, 3), high=20, low=10)
b = torch.randint(size=(3, 3), high=20, low=4)

print(a)
print(b)

tensor([[16, 16, 18],
        [14, 19, 10],
        [17, 19, 12]])
tensor([[ 5, 14, 10],
        [14, 10,  4],
        [14, 11,  6]])


##### if you use addignment operator then its exactly do not copy the tensor value is just reference the previous tensor so if you change in tensor a then tensor b will be automenticly change it. So its does not make any sencec. So use `tensor.clone()` function

In [111]:
a = b

In [112]:
a[0][0] = 0

In [113]:
b

tensor([[ 0, 14, 10],
        [14, 10,  4],
        [14, 11,  6]])

In [114]:
b = a.clone()
b

tensor([[ 0, 14, 10],
        [14, 10,  4],
        [14, 11,  6]])

In [115]:
a[0][0]=99
a

tensor([[99, 14, 10],
        [14, 10,  4],
        [14, 11,  6]])

In [116]:
b

tensor([[ 0, 14, 10],
        [14, 10,  4],
        [14, 11,  6]])

## Tensor Operation on `GPU`

In [117]:
device = torch.device('cuda')
device

device(type='cuda')

In [118]:
## creating a new tensor in GPU
torch.rand((2, 3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [119]:
a

tensor([[99, 14, 10],
        [14, 10,  4],
        [14, 11,  6]])

In [120]:
a.to(device=device)

tensor([[99, 14, 10],
        [14, 10,  4],
        [14, 11,  6]], device='cuda:0')

In [121]:
a + 5

tensor([[104,  19,  15],
        [ 19,  15,   9],
        [ 19,  16,  11]])

## Tensor Reshaping

In [122]:
l = torch.ones(4, 4)

In [123]:
l

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [124]:
l.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [125]:
l.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
## permute operation
m = torch.rand(2, 3, 4)

In [127]:
m

tensor([[[0.9761, 0.5934, 0.3124, 0.9431],
         [0.8519, 0.9815, 0.1132, 0.4783],
         [0.4436, 0.3847, 0.4521, 0.5569]],

        [[0.9952, 0.0015, 0.0813, 0.4907],
         [0.2130, 0.4603, 0.1386, 0.0277],
         [0.5662, 0.3503, 0.6555, 0.7667]]])

In [128]:
m.permute(2, 0, 1)

tensor([[[0.9761, 0.8519, 0.4436],
         [0.9952, 0.2130, 0.5662]],

        [[0.5934, 0.9815, 0.3847],
         [0.0015, 0.4603, 0.3503]],

        [[0.3124, 0.1132, 0.4521],
         [0.0813, 0.1386, 0.6555]],

        [[0.9431, 0.4783, 0.5569],
         [0.4907, 0.0277, 0.7667]]])

## Unsqueeze and squeeze

- add a new dim in the given position

In [129]:
n = torch.rand(256, 256, 3)

In [130]:
n.unsqueeze(0).shape

torch.Size([1, 256, 256, 3])

In [132]:
o = torch.rand(1, 20)

In [133]:
o.squeeze(0).shape

torch.Size([20])

## Travel Numpy to PyTorch Tensor

In [134]:
p = torch.tensor(
    [1, 2, 3, 4]
)

In [135]:
p

tensor([1, 2, 3, 4])

In [136]:
import numpy as np

In [137]:
q = p.numpy()
q

array([1, 2, 3, 4], dtype=int64)

In [138]:
r = np.array(
    [2, 3, 4, 5]
)

In [139]:
r

array([2, 3, 4, 5])

In [140]:
s = torch.from_numpy(r)
s

tensor([2, 3, 4, 5], dtype=torch.int32)