In [1]:
import torch
import math

In [2]:
 x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.5633e-02, 2.0921e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
print('Lab is Working')

Lab is Working


In [12]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


## Random and Seeds

In [13]:
torch.manual_seed(122)
random1 = torch.rand(3, 3)
print(random1)

random2 = torch.rand(3, 3)
print(random2)

torch.manual_seed(122)
random3 = torch.rand(3, 3)
print(random3)

tensor([[0.1899, 0.8691, 0.7658],
        [0.4226, 0.9384, 0.1215],
        [0.6385, 0.7225, 0.4647]])
tensor([[0.8698, 0.5545, 0.1063],
        [0.2686, 0.6807, 0.9143],
        [0.9942, 0.3259, 0.0564]])
tensor([[0.1899, 0.8691, 0.7658],
        [0.4226, 0.9384, 0.1215],
        [0.6385, 0.7225, 0.4647]])


# Tensor Shapes

In [17]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

random_like_x = torch.rand_like(x)
print(random_like_x.shape)
print(random_like_x)

torch.Size([2, 2, 3])
tensor([[[1.5634e-02, 2.0921e-42, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0.8698, 0.5545, 0.1063],
         [0.2686, 0.6807, 0.9143]],

        [[0.9942, 0.3259, 0.0564],
         [0.7371, 0.8574, 0.5293]]])


## Tensor data by user

In [27]:
some_constants = torch.tensor([
    [1, 2, 3, 4],
    [1, 34, 5, 67],
    [1, 3, 45, 55]
])
print(some_constants.shape)
print(some_constants)

some_int = torch.tensor((1, 2, 4, 7,5 ,7, 4, 6, 7))
print(some_int.shape)
print(some_int)

some_1d_int = torch.tensor(
    ([1, 2, 3, 4, 5, 6], [2, 3, 45, 6,7, 5])
    
)
print(some_1d_int.shape)
print(some_1d_int)

torch.Size([3, 4])
tensor([[ 1,  2,  3,  4],
        [ 1, 34,  5, 67],
        [ 1,  3, 45, 55]])
torch.Size([9])
tensor([1, 2, 4, 7, 5, 7, 4, 6, 7])
torch.Size([2, 6])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 2,  3, 45,  6,  7,  5]])


## Tensor Data Types

#### torch.tensor() creates a copy of the data

In [31]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float16) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 7.2266, 12.1797,  2.9980],
        [ 2.6855,  1.3770,  0.3125]], dtype=torch.float16)
tensor([[ 7, 12,  2],
        [ 2,  1,  0]], dtype=torch.int32)
