In [4]:
print("hello")

hello


In [5]:
import torch

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
tows = torch.ones(2, 3)
tows

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
towss = tows * 2
towss

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [17]:
tows + towss

tensor([[3., 3., 3.],
        [3., 3., 3.]])