In [88]:
import torch
import math
import numpy as np

In [89]:
x = torch.arange(4.0, requires_grad=True)
print(x)

tensor([0., 1., 2., 3.], requires_grad=True)


In [90]:
print(x.grad)

None


In [91]:
y = torch.dot(x, x)
print(y)

tensor(14., grad_fn=<DotBackward0>)


In [92]:
y.backward()
print(x.grad)

tensor([0., 2., 4., 6.])


In [93]:
x.grad == 2 * x

tensor([True, True, True, True])

In [94]:
c = torch.arange(5.0, requires_grad=True)
c

tensor([0., 1., 2., 3., 4.], requires_grad=True)

In [95]:
d = c * 2

In [96]:
d

tensor([0., 2., 4., 6., 8.], grad_fn=<MulBackward0>)

In [97]:
e = d.sum()
e

tensor(20., grad_fn=<SumBackward0>)

In [98]:
e.backward()

In [99]:
print(c.grad)

tensor([2., 2., 2., 2., 2.])


In [100]:
x = torch_input=torch.tensor([[1.0,2.0,3.0],
                              [4.0,5.0,6.0],
                              [7.0,8.0,9.0]],requires_grad=True)

In [101]:
def f(x):
    return (x**3) + 7*(x**2) + 5*x + 10

In [102]:
z = f(x).sum()

In [103]:
z

tensor(4335., grad_fn=<SumBackward0>)

In [104]:
z.backward()

In [105]:
print(x.grad)

tensor([[ 22.,  45.,  74.],
        [109., 150., 197.],
        [250., 309., 374.]])
