## 00.PyTorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
 !nvidia-smi

Sat Sep 28 15:34:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.83                 Driver Version: 546.83       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8               3W /  80W |    183MiB /  6141MiB |     28%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu118


## Introduction to Tensor

### creating tensors

In [3]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# MATRIX

matrix = torch.tensor([[1, 2],
                      [3, 4],
                      [7, 8]])
matrix

tensor([[1, 2],
        [3, 4],
        [7, 8]])

In [10]:
matrix.shape

torch.Size([3, 2])

In [11]:
matrix[0]

tensor([1, 2])

In [12]:
matrix[0][1]

tensor(2)

In [13]:
matrix.ndim

2

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 4],
                        [4, 5, 6],
                        [7, 9, 3]]])

In [15]:
TENSOR

tensor([[[1, 2, 4],
         [4, 5, 6],
         [7, 9, 3]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [4, 5, 6],
        [7, 9, 3]])

In [18]:
tensor = torch.tensor([[[1, 2, 4],
                        [4, 5, 6],
                        [7, 9, 3]],
                      [[3, 2, 1],
                       [5, 3, 2],
                       [9, 8, 1]]])

In [19]:
tensor.shape

torch.Size([2, 3, 3])

In [20]:
tensor[1]

tensor([[3, 2, 1],
        [5, 3, 2],
        [9, 8, 1]])

## Random Tensor

Why random tensor?

`Start with rnadom numbers --> look at data --> update random numbers -->look at data and update random number`

In [21]:
# Creating random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1666, 0.3261, 0.7048, 0.8941],
        [0.6872, 0.0540, 0.1618, 0.4837],
        [0.0184, 0.7162, 0.8951, 0.3367]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor3dim = torch.rand(2, 2, 3)
random_tensor3dim

tensor([[[0.8412, 0.5864, 0.0650],
         [0.8047, 0.5716, 0.3083]],

        [[0.3639, 0.5233, 0.0652],
         [0.6666, 0.3492, 0.8377]]])

In [24]:
random_tensor3dim.ndim

3

In [25]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Tensor: Zeros and Ones

In [26]:
# create a tensor all zeros

zero = torch.zeros(2, 3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
# create a tensor all ones

ones = torch.ones(2, 3)

In [28]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
zero * ones

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
ones.dtype

torch.float32

In [31]:
random_image_size_tensor.dtype

torch.float32

# Creating tensor in a range and tensor-like

In [32]:
# Use torch.range()
torch.range(0, 10)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19676\1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
torch.range(start=0, end=1000, step=233)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19676\2618141711.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0, end=1000, step=233)


tensor([  0., 233., 466., 699., 932.])

In [34]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# Creating tensor like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
custom_zeros = torch.ones_like(one_to_ten)
custom_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatype

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensor not right datatype
2. tensor not right shape
3. Tensor not on the right device

In [43]:
# Float 32 tensor

float_32_tensor = torch.tensor([1.0, 2, 3, 4, 5], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = torch.tensor([1., 2., 4., 5., 6.],
                                dtype=torch.float16, # e.g. float16, float32
                                device=None, # cpu, cuda
                                requires_grad=False)

float_16_tensor.dtype

torch.float16

## Getting tensor attributes (info. about tensors)

1. Tensor not right datatype - to get datatype from tensor use `torch.dtype`
2. tensor not right shape - to get tensor shape use `torch.shape`
3. Tensor not on the right device - to get device from tensor use `tensor.device`

In [45]:
float_32_tensor * float_16_tensor

tensor([ 1.,  4., 12., 20., 30.])

In [46]:
int_32_tensors = torch.tensor([1, 2, 3, 4, 5], dtype = torch.int32)

In [47]:
float_16_tensor * int_32_tensors

tensor([ 1.,  4., 12., 20., 30.], dtype=torch.float16)

In [49]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9044, 0.0519, 0.9361, 0.7722],
        [0.3559, 0.2159, 0.4294, 0.8939],
        [0.1944, 0.1433, 0.8943, 0.3383]])

In [51]:
# find out details about some-tensor

print(f"Data type: {some_tensor.dtype} ")
print(f"Shape: {some_tensor.shape} ")
print(f"Devices: {some_tensor.device} ")

Data type: torch.float32 
Shape: torch.Size([3, 4]) 
Devices: cpu 


# Tensor manipulating (tensor operations)

**Tensor operations includes:**
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [53]:
# Create a tensor ana add 10 to it
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor + 10

tensor([11, 12, 13, 14, 15])

In [54]:
# Multipli tensor by 10
mul_10_tensors = tensor * 10
mul_10_tensors

tensor([10, 20, 30, 40, 50])

In [56]:
# substraction
tensor - mul_10_tensors

tensor([ -9, -18, -27, -36, -45])

In [57]:
tensor

tensor([1, 2, 3, 4, 5])

In [58]:
# try out pytorch in-build function
torch.mul(tensor, 10)

tensor([10, 20, 30, 40, 50])

In [60]:
torch.add(tensor, 10)

tensor([11, 12, 13, 14, 15])

## Matrix Multiplication

Two main ways of performing multiplication in **NN** ad **DL**:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [61]:
# Matrix Multiplication
print(tensor, '*', tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])


tensor(55)

In [62]:
# matric multipli by hand

1*1 + 2*2 + 3*3 + 4*4 + 5*5

55

In [63]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(55)
CPU times: total: 0 ns
Wall time: 7.64 ms


In [64]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(55)

## One of the most common error in deep learning: shape errors

**There are tow main rules that performing matrix multipilication needs to satisfy:**
1. The **innner Dimmensions** must match:
   * (3, 2) @ (3, 2) won't work
   * (2, 3) @ (3, 2) will work
   * (3, 2) @ (2, 3) will work
2. The resultin matrix has the shape of the **outer dimensions**
    * `(2, 4) @ (4, 5) and the shape: **(2, 5)**`

In [66]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [68]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[1.0229, 0.7389, 0.2937, 0.2919],
        [1.2232, 0.9046, 0.4077, 0.3816],
        [1.3542, 1.0284, 0.5240, 0.4643]])

In [76]:
a = torch.randint(1, 10, (3, 2))
a

tensor([[2, 9],
        [9, 2],
        [5, 4]])

In [78]:
b = torch.randint(1, 5, (2, 5))
b

tensor([[3, 4, 1, 1, 2],
        [2, 2, 1, 4, 2]])

In [79]:
mul_ab = torch.matmul(a, b)
mul_ab

tensor([[24, 26, 11, 38, 22],
        [31, 40, 11, 17, 22],
        [23, 28,  9, 21, 18]])

In [80]:
mul_ab.shape

torch.Size([3, 5])

A **transpose** switches the axies or dimensions of a given tensor

In [83]:
c = torch.randint(1, 10, (3, 2))
c

tensor([[2, 5],
        [9, 4],
        [3, 5]])

In [84]:
c.T

tensor([[2, 9, 3],
        [5, 4, 5]])

In [85]:
c.T.shape

torch.Size([2, 3])

In [86]:
mul_ac = torch.matmul(a, c)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [88]:
mul_ac = torch.matmul(a, c.T)
mul_ac

tensor([[49, 54, 51],
        [28, 89, 37],
        [30, 61, 35]])

## Tensor aggregation: min, max, mean, sum, etc

In [96]:
## Create a tensor

x = torch.randint(3, 40, (3, 4))
x

tensor([[ 3, 32,  3, 12],
        [30, 24, 14, 13],
        [10, 15, 39, 37]])

In [98]:
x.min()

tensor(3)

In [99]:
torch.max(x)

tensor(39)

In [100]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [103]:
# Find the mean -note: the torch.mean() function requires a tensor of float32, or float16 datatype to work
torch.mean(x.type(torch.float16))

tensor(19.3281, dtype=torch.float16)

In [102]:
x.type(torch.float32).mean()

tensor(19.3333)

In [105]:
# find the sum
x.sum(), torch.sum(x)

(tensor(232), tensor(232))

In [106]:
y = torch.arange(0, 100, 10)
y

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
# find the position in tensor that has the minimum value with agrmin() --> returns the index of the minimum values
y.argmin()

tensor(0)

In [108]:
y[0]

tensor(0)

In [109]:
y[4] = -1

In [110]:
y

tensor([ 0, 10, 20, 30, -1, 50, 60, 70, 80, 90])

In [111]:
y.argmin()

tensor(4)

In [112]:
y[4]

tensor(-1)

In [115]:
# find the position of the maximum tensor that has the maximum value wirh argmax
y.argmax() # return the max valu index

tensor(9)

In [114]:
y[y.argmax()]

tensor(90)

In [116]:
x.argmax()

tensor(10)