## 00.PyTorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
 !nvidia-smi

Fri Sep 27 22:16:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.83                 Driver Version: 546.83       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   40C    P8               3W /  80W |    190MiB /  6141MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu118


## Introduction to Tensor

### creating tensors

In [3]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# MATRIX

matrix = torch.tensor([[1, 2],
                      [3, 4],
                      [7, 8]])
matrix

tensor([[1, 2],
        [3, 4],
        [7, 8]])

In [10]:
matrix.shape

torch.Size([3, 2])

In [11]:
matrix[0]

tensor([1, 2])

In [12]:
matrix[0][1]

tensor(2)

In [13]:
matrix.ndim

2

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 4],
                        [4, 5, 6],
                        [7, 9, 3]]])

In [15]:
TENSOR

tensor([[[1, 2, 4],
         [4, 5, 6],
         [7, 9, 3]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 4],
        [4, 5, 6],
        [7, 9, 3]])

In [18]:
tensor = torch.tensor([[[1, 2, 4],
                        [4, 5, 6],
                        [7, 9, 3]],
                      [[3, 2, 1],
                       [5, 3, 2],
                       [9, 8, 1]]])

In [19]:
tensor.shape

torch.Size([2, 3, 3])

In [20]:
tensor[1]

tensor([[3, 2, 1],
        [5, 3, 2],
        [9, 8, 1]])

## Random Tensor

Why random tensor?

`Start with rnadom numbers --> look at data --> update random numbers -->look at data and update random number`

In [21]:
# Creating random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9576, 0.6978, 0.9021, 0.8446],
        [0.3207, 0.5186, 0.3527, 0.3973],
        [0.1695, 0.2693, 0.3684, 0.0375]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor3dim = torch.rand(2, 2, 3)
random_tensor3dim

tensor([[[0.3530, 0.0697, 0.8107],
         [0.0418, 0.5624, 0.9081]],

        [[0.3858, 0.4113, 0.6790],
         [0.5452, 0.3306, 0.1663]]])

In [24]:
random_tensor3dim.ndim

3

In [25]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Tensor: Zeros and Ones

In [26]:
# create a tensor all zeros

zero = torch.zeros(2, 3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
# create a tensor all ones

ones = torch.ones(2, 3)

In [28]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
zero * ones

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
ones.dtype

torch.float32

In [31]:
random_image_size_tensor.dtype

torch.float32

# Creating tensor in a range and tensor-like

In [32]:
# Use torch.range()
torch.range(0, 10)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13680\1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
torch.range(start=0, end=1000, step=233)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13680\2618141711.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0, end=1000, step=233)


tensor([  0., 233., 466., 699., 932.])

In [35]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Creating tensor like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
custom_zeros = torch.ones_like(one_to_ten)
custom_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatype

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensor not right datatype
2. tensor not right shape
3. Tensor not on the right device

In [42]:
# Float 32 tensor

float_32_tensor = torch.tensor([1.0, 2, 3, 4, 5], dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [47]:
float_16_tensor = torch.tensor([1., 2., 4., ],
                                dtype=torch.float16, # e.g. float16, float32
                                device=None, # cpu, cuda
                                requires_grad=False)

float_16_tensor.dtype

torch.float16

In [ ]:
## 2