In [1]:
import torch

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [3]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [8]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [9]:
x_rereshape = x.reshape(9, 1)
x_rereshape, x_rereshape.shape, x_rereshape.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [14]:
x_again = torch.arange(1., 13,)
x_again, x_again.shape, x_again.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]),
 1)

In [12]:
x_again.reshape(2, 5)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [13]:
x_again.reshape(5, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [15]:
x_again.reshape(3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

# Change the view

In [17]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [18]:
# Changing z changes x (because a view of a tensor shares the same memore as the original input)

z[:, 0] = 4
z, x

(tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [19]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[4., 4., 4.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

# Squeezing, Unsqueezing and permutin tensors

In [ ]:
3: