# *Code Flow*

1. Load the dataset
2. Basic Programming
3. Training Process
    - Create the Model
    - Forward Pass
    - Loss Calculation
    - Backward Pass
    - Parameters Update
4. Model evaluation

In [2]:
## import some all necessary module
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(4)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
272  8910988         M        21.75         20.99          147.30     1491.0   
109   864018         B        11.34         21.26           72.48      396.5   
242   883852         B        11.30         18.19           73.93      389.4   
121    86517         M        18.66         17.12          121.40     1077.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
272          0.09401           0.19610         0.21950              0.10880   
109          0.08759           0.06575         0.05133              0.01899   
242          0.09592           0.13250         0.15480              0.02854   
121          0.10540           0.11000         0.14570              0.08665   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
272  ...          28.18           195.90      2384.0            0.1272   
109  ...          29.15            83.99       518.1            0.1699   
242  ...          27.96            87.16       472.9            0.1347   
121  ...          24.90           145.40      1549.0            0.1503   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
272             0.4725           0.5807               0.18410          0.2833   
109             0.2196           0.3120               0.08278          0.2829   
242             0.4848           0.7436               0.12180          0.3308   
121             0.2291           0.3272               0.16740          0.2894   

     fractal_dimension_worst  Unnamed: 32  
272                  0.08858          NaN  
109                  0.08832          NaN  
242                  0.12970          NaN  
121                  0.08456          NaN  

[4 rows x 33 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [7]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.sample(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
370         M        16.35         23.29           109.0      840.4   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
370          0.09742            0.1497          0.1811              0.08773   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
370         0.2175  ...         19.38          31.03            129.3   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
370      1165.0            0.1415             0.4665           0.7087   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
370                0.2248          0.4824                  0.09614  

[1 rows x 31 columns]

In [8]:
df.shape

(569, 31)

In [9]:
X = df.iloc[:, 1:]
X.head(2)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [10]:
y = df.iloc[:, 0]
y.head(1)

0    M
Name: diagnosis, dtype: object

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## *Scaling*

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [14]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

#### All varivable are numpy array to need to transform to Tensor because we build the model into the PyTorch

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_test_tensor

tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]],
       dtype=torch.float64)

# *Defining The Model*

In [38]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
        
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        ## Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        ## calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameter

In [42]:
learning_rate = 0.1
epochs = 250


# *Training Pipeline*

In [43]:
## create model

model = MySimpleNN(X_train_tensor)

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model.forward(X_train_tensor)
    

    ## loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    # print(loss)

    ## backward pass
    loss.backward()

    ## update the weight
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    ## zero gradients because next epo not effect the previous grad value
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 3.7110359531768435
Epoch 2, Loss: 3.5848742711080255
Epoch 3, Loss: 3.4548895274489575
Epoch 4, Loss: 3.3214231890712016
Epoch 5, Loss: 3.180488693241925
Epoch 6, Loss: 3.035187136196122
Epoch 7, Loss: 2.8847955196550097
Epoch 8, Loss: 2.727789453349685
Epoch 9, Loss: 2.5674240991995068
Epoch 10, Loss: 2.407730100542444
Epoch 11, Loss: 2.2516180289140446
Epoch 12, Loss: 2.0931939601468312
Epoch 13, Loss: 1.9317642167636377
Epoch 14, Loss: 1.7743232473710628
Epoch 15, Loss: 1.6219947112183764
Epoch 16, Loss: 1.478533270704421
Epoch 17, Loss: 1.346272935996332
Epoch 18, Loss: 1.2272942131575757
Epoch 19, Loss: 1.1256197813826598
Epoch 20, Loss: 1.041844323030881
Epoch 21, Loss: 0.9753494384410955
Epoch 22, Loss: 0.924273742101668
Epoch 23, Loss: 0.8858765341484452
Epoch 24, Loss: 0.857175560263223
Epoch 25, Loss: 0.8355020300625249
Epoch 26, Loss: 0.8187592388450625
Epoch 27, Loss: 0.805435912326255
Epoch 28, Loss: 0.7945013071051977
Epoch 29, Loss: 0.7852735213294412
Epoc

In [44]:
model.weights

tensor([[ 0.2068],
        [-0.0544],
        [ 0.3239],
        [-0.3189],
        [-0.0045],
        [-0.2561],
        [-0.0259],
        [-0.2471],
        [-0.0216],
        [ 0.1989],
        [-0.3910],
        [ 0.0190],
        [ 0.1547],
        [ 0.2879],
        [-0.0639],
        [ 0.2812],
        [-0.2293],
        [ 0.0340],
        [-0.0215],
        [ 0.1111],
        [-0.3308],
        [ 0.0576],
        [ 0.0817],
        [ 0.2216],
        [ 0.1352],
        [-0.3462],
        [ 0.2248],
        [ 0.1921],
        [ 0.1072],
        [-0.1161]], dtype=torch.float64, requires_grad=True)

## *Model evaluation*

In [51]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.6206524968147278
