In [1]:
import torch
import math

In [2]:
 x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
print('Lab is Working')

Lab is Working


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


## Random and Seeds

In [5]:
torch.manual_seed(122)
random1 = torch.rand(3, 3)
print(random1)

random2 = torch.rand(3, 3)
print(random2)

torch.manual_seed(122)
random3 = torch.rand(3, 3)
print(random3)

tensor([[0.1899, 0.8691, 0.7658],
        [0.4226, 0.9384, 0.1215],
        [0.6385, 0.7225, 0.4647]])
tensor([[0.8698, 0.5545, 0.1063],
        [0.2686, 0.6807, 0.9143],
        [0.9942, 0.3259, 0.0564]])
tensor([[0.1899, 0.8691, 0.7658],
        [0.4226, 0.9384, 0.1215],
        [0.6385, 0.7225, 0.4647]])


# Tensor Shapes

In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

random_like_x = torch.rand_like(x)
print(random_like_x.shape)
print(random_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0.8698, 0.5545, 0.1063],
         [0.2686, 0.6807, 0.9143]],

        [[0.9942, 0.3259, 0.0564],
         [0.7371, 0.8574, 0.5293]]])


## Tensor data by user

In [7]:
some_constants = torch.tensor([
    [1, 2, 3, 4],
    [1, 34, 5, 67],
    [1, 3, 45, 55]
])
print(some_constants.shape)
print(some_constants)

some_int = torch.tensor((1, 2, 4, 7,5 ,7, 4, 6, 7))
print(some_int.shape)
print(some_int)

some_1d_int = torch.tensor(
    ([1, 2, 3, 4, 5, 6], [2, 3, 45, 6,7, 5])
    
)
print(some_1d_int.shape)
print(some_1d_int)

torch.Size([3, 4])
tensor([[ 1,  2,  3,  4],
        [ 1, 34,  5, 67],
        [ 1,  3, 45, 55]])
torch.Size([9])
tensor([1, 2, 4, 7, 5, 7, 4, 6, 7])
torch.Size([2, 6])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 2,  3, 45,  6,  7,  5]])


## Tensor Data Types

#### torch.tensor() creates a copy of the data

In [8]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float16) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 7.2266, 12.1797,  2.9980],
        [ 2.6855,  1.3770,  0.3125]], dtype=torch.float16)
tensor([[ 7, 12,  2],
        [ 2,  1,  0]], dtype=torch.int32)


## Math & Logic with PyTorch Tensor

In [14]:
ones = torch.ones(2, 3) + 1
tows = torch.zeros(2, 3) + 40
threes = torch.rand(3, 3) * 3
fours = ones ** 3

print(ones)
print(tows)
print(threes)
print(fours)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[40., 40., 40.],
        [40., 40., 40.]])
tensor([[2.7492, 2.9901, 0.3687],
        [2.3535, 2.4160, 1.9571],
        [2.7863, 1.2011, 0.6732]])
tensor([[8., 8., 8.],
        [8., 8., 8.]])


In [15]:
a = torch.ones(2, 3)
b = torch.ones(2, 3)

print(a + b)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [29]:
a = torch.ones(4, 3, 2) + 2
# print(a)
b = a * torch.ones( 3, 2) + 1
print(b)

c = a * torch.rand(3, 1)
print(c)


tensor([[[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]]])
tensor([[[0.6010, 0.6010],
         [1.2598, 1.2598],
         [1.1961, 1.1961]],

        [[0.6010, 0.6010],
         [1.2598, 1.2598],
         [1.1961, 1.1961]],

        [[0.6010, 0.6010],
         [1.2598, 1.2598],
         [1.1961, 1.1961]],

        [[0.6010, 0.6010],
         [1.2598, 1.2598],
         [1.1961, 1.1961]]])


## More Math With Tensor

In [30]:
a = torch.rand(2, 4) * 2 - 1
print('Common Functions: ')

print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -.5, 0.5))

Common Functions: 
tensor([[0.2237, 0.2567, 0.8991, 0.0963],
        [0.1253, 0.4079, 0.2787, 0.4276]])
tensor([[1., 1., -0., 1.],
        [-0., 1., -0., -0.]])
tensor([[ 0.,  0., -1.,  0.],
        [-1.,  0., -1., -1.]])
tensor([[ 0.2237,  0.2567, -0.5000,  0.0963],
        [-0.1253,  0.4079, -0.2787, -0.4276]])


### Trigometric Function and their invers

In [31]:
angles = torch.tensor([0, math.pi/4, math.pi/2, 3 * math.pi/4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)


Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


### Bitwise Operations

In [33]:
b = torch.tensor([[1, 2], [1, 4]])
c = torch.tensor([[1, 3], [1, 4]])

print(torch.bitwise_xor(b, c))

tensor([[0, 1],
        [0, 0]])


In [34]:
a = torch.ones(2, 3)
b = torch.zeros(2, 3)

print(torch.eq(a, b))

tensor([[False, False, False],
        [False, False, False]])


In [35]:
a = torch.ones(2, 3) - 1
b = torch.zeros(2, 3)

print(torch.eq(a, b))

tensor([[True, True, True],
        [True, True, True]])


In [40]:
d = torch.tensor([[1, 2, 3, 4], [2, 3, 5, 6]], dtype=torch.float64)

print(torch.max(d))

tensor(6., dtype=torch.float64)


In [38]:
torch.max(d).item()

6

In [41]:
torch.mean(d)

tensor(3.2500, dtype=torch.float64)

In [42]:
torch.std(d)

tensor(1.6690, dtype=torch.float64)

In [43]:
torch.prod(d)

tensor(4320., dtype=torch.float64)

In [44]:
torch.unique(torch.tensor([1, 2, 1, 2, 3, 2, 2]))

tensor([1, 2, 3])

## Vector and Liner algebra Operations

In [46]:
v1 = torch.tensor([1., 0., 0.])
v2 = torch.tensor([0., 1., 0.])

m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]])

print(torch.linalg.cross(v1, v2))
print(m1)


tensor([0., 0., 1.])
tensor([[0.9269, 0.7869],
        [0.1006, 0.1454]])


In [50]:
m3 = torch.linalg.matmul(m1, m2)
m3

tensor([[2.7806, 2.3606],
        [0.3017, 0.4361]])

In [51]:
print(torch.svd(m3))

torch.return_types.svd(
U=tensor([[-0.9903, -0.1393],
        [-0.1393,  0.9903]]),
S=tensor([3.6833, 0.1359]),
V=tensor([[-0.7590, -0.6511],
        [-0.6511,  0.7590]]))
