In [5]:
import pandas as pd
import numpy as np
import torch.nn as nn
import torch

In [ ]:
class Model(nn.Module):
    def __init__(self, num_features, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.liner = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.liner(features)
        out = self.sigmoid(out)

        return out

In [6]:
## create dataset
features = torch.rand(10, 5)

## create model
model = Model(features.shape[1])
## call model for forward pass
model(features)
## show model weight

tensor([[0.6516],
        [0.6452],
        [0.6293],
        [0.6651],
        [0.6584],
        [0.6207],
        [0.6137],
        [0.6313],
        [0.6282],
        [0.6569]], grad_fn=<SigmoidBackward0>)

In [7]:
model.liner.weight

Parameter containing:
tensor([[ 0.1434, -0.0856, -0.3072,  0.2981,  0.2214]], requires_grad=True)

In [8]:
model.liner.bias

Parameter containing:
tensor([0.4288], requires_grad=True)

In [9]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## **Build my own NN**

In [10]:
class Model(nn.Module):
    def __init__(self, num_features, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.liner1 = nn.Linear(in_features=num_features, out_features=3)
        self.relu = nn.ReLU()
        self.liner2 = nn.Linear(in_features=3, out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.liner1(features)
        out = self.relu(out)
        out = self.liner2(out)
        out = self.sigmoid(out)

        return out

In [12]:
model = Model(features.shape[1])

In [13]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00