In [1]:
import numpy as np

In [2]:
v = np.array([1, -1, 2])
w = np.array([2, 5, 2])

In [3]:
print(v + w)

[3 4 4]


In [4]:
print(v - w)

[-1 -6  0]


# Scalar Multi:

In [5]:
print(v * 3)

[ 3 -3  6]


In [6]:
# Finding Length of a vector

print(np.linalg.norm(v))

2.449489742783178


In [7]:
s = np.dot(v, w)
s

1