In [1]:
import numpy as np

In [8]:
p = np.array([
    [1, 7],
    [2, 1],
    [3, 2]
])
q = np.array([
    [1, 1],
    [1, -1],
    [1, 0]
])

In [3]:
p

array([[1, 7],
       [2, 1],
       [3, 2]])

In [6]:
q

array([[ 1,  1],
       [ 1, -1]])

In [11]:
addition = np.add(p, q)
addition

array([[2, 8],
       [3, 0],
       [4, 2]])

In [13]:
r = np.array([
    [1, 3, 1],
    [1, 0, 1]
])

In [14]:
dot_products = np.dot(p, r)

In [15]:
dot_products

array([[8, 3, 8],
       [3, 6, 3],
       [5, 9, 5]])

In [16]:
det = np.linalg.det(dot_products)

In [17]:
det

0.0

In [18]:
s2 = np.linalg.inv(dot_products)

LinAlgError: Singular matrix

In [19]:
m = np.array([[1, -1], [2, 3]])

In [22]:
m_inv = np.linalg.inv(m)
m_inv

array([[ 0.6,  0.2],
       [-0.4,  0.2]])