In [2]:
import torch
import math

In [8]:
a = torch.ones(2, 2)
b = a
print(a)
print(b)
a[0][1] = 99
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[ 1., 99.],
        [ 1.,  1.]])
tensor([[ 1., 99.],
        [ 1.,  1.]])


In [9]:
a = torch.ones(2, 2)
b = a.clone()
print(a)
print(b)
a[0][1] = 99
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[ 1., 99.],
        [ 1.,  1.]])
tensor([[1., 1.],
        [1., 1.]])


## Moving To GPU

In [10]:
if torch.cuda.is_available():
    print("GPU, I'm hare")
else:
    print("no GPu")

GPU, I'm hare


In [12]:
# Python program to squeeze the tensor
# importing torch
# import torch

# creating the input tensor
input = torch.randn(3,1,2,1,4)
# print the input tensor
print("Input tensor Size:\n",input.size())

# squeeze the tensor
output = torch.squeeze(input)
# print the squeezed tensor
print("Size after squeeze:\n",output.size())


Input tensor Size:
 torch.Size([3, 1, 2, 1, 4])
Size after squeeze:
 torch.Size([3, 2, 4])


In [14]:
a = torch.rand(1, 20)
print(a)
print(a.shape)
b = a.squeeze(0)
print(b.shape)
print(b)

tensor([[0.1327, 0.4213, 0.9611, 0.1384, 0.1086, 0.0099, 0.5810, 0.6358, 0.6904,
         0.4721, 0.2083, 0.6111, 0.4191, 0.3841, 0.2069, 0.6499, 0.6970, 0.9159,
         0.3978, 0.6909]])
torch.Size([1, 20])
torch.Size([20])
tensor([0.1327, 0.4213, 0.9611, 0.1384, 0.1086, 0.0099, 0.5810, 0.6358, 0.6904,
        0.4721, 0.2083, 0.6111, 0.4191, 0.3841, 0.2069, 0.6499, 0.6970, 0.9159,
        0.3978, 0.6909])


In [22]:
a = torch.ones(4, 3, 2)
print(a)
b = torch.rand( 3) * 10
print(b)
c = b.unsqueeze(1)
print(c)
print(c.shape)

print(a * c)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([9.3924, 3.6809, 4.8752])
tensor([[9.3924],
        [3.6809],
        [4.8752]])
torch.Size([3, 1])
tensor([[[9.3924, 9.3924],
         [3.6809, 3.6809],
         [4.8752, 4.8752]],

        [[9.3924, 9.3924],
         [3.6809, 3.6809],
         [4.8752, 4.8752]],

        [[9.3924, 9.3924],
         [3.6809, 3.6809],
         [4.8752, 4.8752]],

        [[9.3924, 9.3924],
         [3.6809, 3.6809],
         [4.8752, 4.8752]]])


# NumPy Bridhe

In [23]:
import numpy as np

In [26]:
numpy_array = np.ones((2, 3))
numpy_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
numpy_array[1, 1] = 99
numpy_array

array([[ 1.,  1.,  1.],
       [ 1., 99.,  1.]])

In [30]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)
print()
numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.7083, 0.8730, 0.1526],
        [0.4478, 0.5718, 0.0923]])

[[0.708265   0.8729745  0.15264481]
 [0.44775528 0.57180357 0.09234351]]


In [31]:
pytorch_tensor = torch.from_numpy(numpy_array)
pytorch_tensor

tensor([[ 1.,  1.,  1.],
        [ 1., 99.,  1.]], dtype=torch.float64)

In [32]:
pytorch_rand[1, 1] = 99
pytorch_rand

tensor([[7.0827e-01, 8.7297e-01, 1.5264e-01],
        [4.4776e-01, 9.9000e+01, 9.2344e-02]])