In [3]:
import torch

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [4]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [5]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [6]:
x_rereshape = x.reshape(9, 1)
x_rereshape, x_rereshape.shape, x_rereshape.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [7]:
x_again = torch.arange(1., 13,)
x_again, x_again.shape, x_again.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]),
 1)

In [8]:
x_again.reshape(2, 5)

RuntimeError: shape '[2, 5]' is invalid for input of size 12

In [9]:
x_again.reshape(5, 2)

RuntimeError: shape '[5, 2]' is invalid for input of size 12

In [10]:
x_again.reshape(3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

# Change the view

In [11]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [12]:
# Changing z changes x (because a view of a tensor shares the same memore as the original input)

z[:, 0] = 4
z, x

(tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [13]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [14]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[4., 4., 4.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

# Squeezing, Unsqueezing and permutin tensors

In [15]:
x_reshaped

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [16]:
# torch.squeeze() removes all single dimensions from the target tensor

print(f"Previous tensor: {x_reshaped} ")
print(f"Previous shape: {x_reshaped.shape} ")

# Remove extra dimensions from x reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNEW tensor: {x_squeezed} ")
print(f"NEW shape: {x_squeezed.shape} ")

Previous tensor: tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Previous shape: torch.Size([1, 9]) 

NEW tensor: tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]) 
NEW shape: torch.Size([9]) 


# torch.unsqueeze() -adds a single dimnension to a target tensor at a specific dim (dimension)

In [19]:
print(f"Previors target: {x_squeezed}")
print(f"Previors shaperd: {x_squeezed.shape}")
print()

# add an extra dim with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNEw Tensor: {x_unsqueezed} ")
print(f"NEw Tensor shaped: {x_unsqueezed.shape} ")

Previors target: tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.])
Previors shaperd: torch.Size([9])


NEw Tensor: tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
NEw Tensor shaped: torch.Size([1, 9]) 


# torch.permute - rearragnges the dim of a target tensor in a specified order

In [21]:
x_original = torch.rand(224, 224, 3) # [height, width, color channel-RGB]

# Permute the original tensor to rearragne the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1) # shigts 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape} ")
print(f"New shape: {x_permuted.shape} ")

# permute work as a view like its share the memory

Previous shape: torch.Size([224, 224, 3]) 
New shape: torch.Size([3, 224, 224]) 


## Selecting data form tensor(indexing)
indexing with PyTorch to indexing with NumPy

In [22]:
x_original[0, 0, 0] = 9
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(9.), tensor(9.))

In [24]:
# Creating tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [25]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
x[0][1][2]

tensor(6)

In [29]:
x[0][1]

tensor([4, 5, 6])

In [28]:
x[0, 1, 2]

tensor(6)

In [30]:
# access number 9
x[0, 2, 2]

tensor(9)

In [31]:
x[:, 2, 2]

tensor([9])

In [34]:
# get index o of 0th 1st dim and all values of 2nd dim

x[0, 0, :]

tensor([1, 2, 3])

In [35]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy
Numpy is popular scientific Python numerical computing library.

* Data in Numpy, want in pythorch tensor --> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NUMPY --> `torch.Tensor.numpy()`

In [36]:
# NumPy array to tensor
import numpy as np

In [38]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [39]:
array.dtype

dtype('float64')

In [42]:
# change the value of array
array = array + 2
array, tensor

(array([ 7.,  8.,  9., 10., 11., 12., 13.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [44]:
numpy_tensor.dtype

dtype('float32')

# Change the tensor, to see what happens to `numpy_tensor`?

In [45]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [1]:
import torch

## Reproducbility (trying to take random out of random)

To reduce the randomness in neural networks and PyTorch comes the oncept of a **random seed**.
Essentially what the random seed does is "flavour the randomness."

In [4]:
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print()
print(random_tensor_a == random_tensor_b)

tensor([[0.1121, 0.1398, 0.1166, 0.9165],
        [0.8303, 0.0171, 0.4239, 0.7844],
        [0.8946, 0.9953, 0.2092, 0.0111]])
tensor([[0.8130, 0.1184, 0.8583, 0.8153],
        [0.8312, 0.2527, 0.9039, 0.8214],
        [0.7341, 0.7908, 0.5836, 0.8447]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [6]:
# leats make some random but reproducible tensors

# Set the random seed
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3, 4)
print(random_tensor_c)

torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3, 4)
print(random_tensor_d)
print()
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Getting a GPU

https://timdettmers.com/category/deep-learning/

cloud computin -GCP, AWS, Azure

In [7]:
torch.cuda.is_available()

True

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [9]:
torch.cuda.device_count()

1

doc: https://pytorch.org/docs/stable/notes/cuda.html

## Putting tensors (and models) on the GPU

the reson we want out tensors/models on the gpu is because using a GPU results in faster computeations.

In [11]:
# create a tensor (Defafult on the CPU)

tensor = torch.tensor([1,2 ,3],)

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [12]:
# move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving tensor back to the cpu

In [13]:
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [14]:
# to fix the gpu tensor with Numpy issues we can first set it oto the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)