# *Code Flow*

1. Load the dataset
2. Basic Programming
3. Training Process
    - Create the Model
    - Forward Pass
    - Loss Calculation
    - Backward Pass
    - Parameters Update
4. Model evaluation

In [1]:
## import some all necessary module
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.sample(4)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
539  921362         B        7.691         25.44           48.34      170.4   
195  875878         B       12.910         16.33           82.53      516.4   
310  893783         B       11.700         19.11           74.33      418.7   
142  869218         B       11.430         17.31           73.66      398.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
539          0.08668           0.11990         0.09252              0.01364   
195          0.07941           0.05366         0.03873              0.02377   
310          0.08814           0.05253         0.01583              0.01148   
142          0.10920           0.09486         0.02031              0.01861   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
539  ...          31.89            54.49       223.6            0.1596   
195  ...          22.00            90.81       600.6            0.1097   
310  ...          26.55            80.92       483.1            0.1223   
142  ...          26.76            82.66       503.0            0.1413   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
539             0.3064          0.33930               0.05000          0.2790   
195             0.1506          0.17640               0.08235          0.3024   
310             0.1087          0.07915               0.05741          0.3487   
142             0.1792          0.07708               0.06402          0.2584   

     fractal_dimension_worst  Unnamed: 32  
539                  0.10660          NaN  
195                  0.06949          NaN  
310                  0.06958          NaN  
142                  0.08096          NaN  

[4 rows x 33 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.sample(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
525         B        8.571          13.1           54.53      221.3   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
525           0.1036           0.07632         0.02565               0.0151   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
525         0.1678  ...         9.473          18.45             63.3   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
525       275.6            0.1641             0.2235           0.1754   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
525               0.08512          0.2983                   0.1049  

[1 rows x 31 columns]

In [5]:
df.shape

(569, 31)

In [6]:
X = df.iloc[:, 1:]
X.head(2)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [8]:
y = df.iloc[:, 0]
y.head(1)

0    M
Name: diagnosis, dtype: object

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## *Scaling*

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [12]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

#### All varivable are numpy array to need to transform to Tensor because we build the model into the PyTorch

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_test_tensor

tensor([[-0.4665, -0.1373, -0.4442,  ..., -0.1944,  0.1728,  0.2037],
        [ 1.3654,  0.4987,  1.3055,  ...,  0.9918, -0.5612, -1.0084],
        [ 0.3801,  0.0692,  0.4041,  ...,  0.5704, -0.1078, -0.2063],
        ...,
        [-0.7355, -0.9985, -0.7414,  ..., -0.2774, -0.3821, -0.3241],
        [ 0.0290,  2.0334,  0.0275,  ..., -0.4903, -1.6091, -0.3314],
        [ 1.8722,  2.8008,  1.8035,  ...,  0.7926, -0.0587, -0.0947]],
       dtype=torch.float64)

## *Convert float64 to float32 format Because i use `nn.Linear`*

In [26]:
X_train_tensor = X_train_tensor.to(torch.float32)
y_train_tensor = y_train_tensor.to(torch.float32)


In [31]:
X_test_tensor = X_test_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

# *Defining The Model*

In [27]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.liner = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.liner(features)
        y_pred = self.sigmoid(out)
        return y_pred
    
    def loss_function(self, y_pred, y):
        ## Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        ## calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameter

In [24]:
learning_rate = 0.1
epochs = 250


# *Training Pipeline*

In [28]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model(X_train_tensor)
    

    ## loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    # print(loss)

    ## backward pass
    loss.backward()

    ## update the weight
    with torch.no_grad():
        model.liner.weight -= learning_rate * model.liner.weight.grad
        model.liner.bias -= learning_rate * model.liner.bias.grad
    
    ## zero gradients because next epo not effect the previous grad value
    model.liner.weight.grad.zero_()
    model.liner.bias.grad.zero_()
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.7087148427963257
Epoch 2, Loss: 0.7043753862380981
Epoch 3, Loss: 0.7008599042892456
Epoch 4, Loss: 0.6979072690010071
Epoch 5, Loss: 0.6953585147857666
Epoch 6, Loss: 0.6931136250495911
Epoch 7, Loss: 0.6911070346832275
Epoch 8, Loss: 0.6892938613891602
Epoch 9, Loss: 0.6876417994499207
Epoch 10, Loss: 0.6861266493797302
Epoch 11, Loss: 0.6847297549247742
Epoch 12, Loss: 0.6834361553192139
Epoch 13, Loss: 0.6822339296340942
Epoch 14, Loss: 0.6811131834983826
Epoch 15, Loss: 0.6800655722618103
Epoch 16, Loss: 0.6790841817855835
Epoch 17, Loss: 0.6781630516052246
Epoch 18, Loss: 0.6772969961166382
Epoch 19, Loss: 0.6764815449714661
Epoch 20, Loss: 0.6757127642631531
Epoch 21, Loss: 0.6749870181083679
Epoch 22, Loss: 0.6743015050888062
Epoch 23, Loss: 0.6736531853675842
Epoch 24, Loss: 0.6730396151542664
Epoch 25, Loss: 0.6724584698677063
Epoch 26, Loss: 0.6719077825546265
Epoch 27, Loss: 0.6713855266571045
Epoch 28, Loss: 0.6708901524543762
Epoch 29, Loss: 0.67041981220

In [29]:
model.liner.weight

Parameter containing:
tensor([[-0.1081, -0.0419,  0.0156,  0.0737,  0.0643,  0.0924,  0.0634, -0.1718,
         -0.0118, -0.0703, -0.0120,  0.0236, -0.1100,  0.1124,  0.0575, -0.0068,
         -0.0126,  0.0430, -0.0169, -0.0609,  0.1310,  0.0305, -0.0564, -0.0307,
         -0.1279, -0.0926, -0.0297,  0.0871,  0.0279,  0.1470]],
       requires_grad=True)

## *Model evaluation*

In [32]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.6228070259094238


## ***Use build in Loss function and Optimizer***

In [33]:
## import loss function
loss_function = nn.BCELoss()

In [34]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.liner = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.liner(features)
        y_pred = self.sigmoid(out)
        return y_pred
    
    

In [36]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model(X_train_tensor)
    

    ## loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    # print(loss)

    ## backward pass
    loss.backward()

    ## update the weight
    with torch.no_grad():
        model.liner.weight -= learning_rate * model.liner.weight.grad
        model.liner.bias -= learning_rate * model.liner.bias.grad
    
    ## zero gradients because next epo not effect the previous grad value
    model.liner.weight.grad.zero_()
    model.liner.bias.grad.zero_()
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.6201720237731934
Epoch 2, Loss: 0.5252720713615417
Epoch 3, Loss: 0.461627721786499
Epoch 4, Loss: 0.4155331552028656
Epoch 5, Loss: 0.3803398311138153
Epoch 6, Loss: 0.3524306118488312
Epoch 7, Loss: 0.32966408133506775
Epoch 8, Loss: 0.31068602204322815
Epoch 9, Loss: 0.29459330439567566
Epoch 10, Loss: 0.28075671195983887
Epoch 11, Loss: 0.2687221169471741
Epoch 12, Loss: 0.2581518888473511
Epoch 13, Loss: 0.248788982629776
Epoch 14, Loss: 0.24043379724025726
Epoch 15, Loss: 0.23292861878871918
Epoch 16, Loss: 0.22614695131778717
Epoch 17, Loss: 0.21998625993728638
Epoch 18, Loss: 0.21436244249343872
Epoch 19, Loss: 0.2092057466506958
Epoch 20, Loss: 0.20445790886878967
Epoch 21, Loss: 0.2000700831413269
Epoch 22, Loss: 0.19600072503089905
Epoch 23, Loss: 0.1922144740819931
Epoch 24, Loss: 0.18868109583854675
Epoch 25, Loss: 0.1853744387626648
Epoch 26, Loss: 0.18227189779281616
Epoch 27, Loss: 0.17935392260551453
Epoch 28, Loss: 0.17660321295261383
Epoch 29, Loss: 

In [37]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5301631093025208


## *Import torch optim SDG, Adam and build most efficient model*

In [38]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model(X_train_tensor)
    

    ## loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    # print(loss)

    ## backward pass
    loss.backward()

    ## update the weight
    optimizer.step()
    # with torch.no_grad():
    #     model.liner.weight -= learning_rate * model.liner.weight.grad
    #     model.liner.bias -= learning_rate * model.liner.bias.grad
    
    ## zero gradients because next epo not effect the previous grad value
    optimizer.zero_grad()
    # model.liner.weight.grad.zero_()
    # model.liner.bias.grad.zero_()
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.5509341359138489
Epoch 2, Loss: 0.2882210910320282
Epoch 3, Loss: 0.18227732181549072
Epoch 4, Loss: 0.1325417011976242
Epoch 5, Loss: 0.10971025377511978
Epoch 6, Loss: 0.09748745709657669
Epoch 7, Loss: 0.08983049541711807
Epoch 8, Loss: 0.08452744781970978
Epoch 9, Loss: 0.08061633259057999
Epoch 10, Loss: 0.077623151242733
Epoch 11, Loss: 0.07528086751699448
Epoch 12, Loss: 0.07341507822275162
Epoch 13, Loss: 0.07189983129501343
Epoch 14, Loss: 0.07064135372638702
Epoch 15, Loss: 0.06956980377435684
Epoch 16, Loss: 0.06863193958997726
Epoch 17, Loss: 0.06778591871261597
Epoch 18, Loss: 0.06699992716312408
Epoch 19, Loss: 0.06625352054834366
Epoch 20, Loss: 0.06553828716278076
Epoch 21, Loss: 0.06485632061958313
Epoch 22, Loss: 0.06421637535095215
Epoch 23, Loss: 0.06362923979759216
Epoch 24, Loss: 0.06310335546731949
Epoch 25, Loss: 0.06264166533946991
Epoch 26, Loss: 0.062240201979875565
Epoch 27, Loss: 0.06188833713531494
Epoch 28, Loss: 0.06157079339027405
Epoch

# ***Most clean Code***

In [39]:
## create model

model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

## define the loop
for epoch in range(epochs):
    ## forward pass
    y_pred = model(X_train_tensor)
    

    ## loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
    

    ## zero gradients because next epo not effect the previous grad value
    optimizer.zero_grad() ## best practice
    
    ## backward pass
    loss.backward()

    ## update the weight
    optimizer.step()
    
    
    ## print loss in each epochs
    print(f"Epoch {epoch + 1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.5582978129386902
Epoch 2, Loss: 0.26780498027801514
Epoch 3, Loss: 0.18791930377483368
Epoch 4, Loss: 0.14582426846027374
Epoch 5, Loss: 0.1191539391875267
Epoch 6, Loss: 0.10365068167448044
Epoch 7, Loss: 0.09474170207977295
Epoch 8, Loss: 0.08919493854045868
Epoch 9, Loss: 0.08546321839094162
Epoch 10, Loss: 0.08276034891605377
Epoch 11, Loss: 0.08063481748104095
Epoch 12, Loss: 0.07881239056587219
Epoch 13, Loss: 0.07713581621646881
Epoch 14, Loss: 0.07553503662347794
Epoch 15, Loss: 0.07400429993867874
Epoch 16, Loss: 0.07257981598377228
Epoch 17, Loss: 0.07131598889827728
Epoch 18, Loss: 0.07025928050279617
Epoch 19, Loss: 0.06942432373762131
Epoch 20, Loss: 0.06878510117530823
Epoch 21, Loss: 0.06828722357749939
Epoch 22, Loss: 0.0678694024682045
Epoch 23, Loss: 0.06747937202453613
Epoch 24, Loss: 0.06708035618066788
Epoch 25, Loss: 0.06665144860744476
Epoch 26, Loss: 0.06618565320968628
Epoch 27, Loss: 0.0656869187951088
Epoch 28, Loss: 0.06516709178686142
Epoch