# ***Plan of attack in this Module***
- Building the neural network using nn module
- Using built-in activation function
- Using built in loss function
- Use built in optimizer

In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn

### *Build the Model class*

In [ ]:
class Model(nn.Module):
    def __init__(self, num_features, ):
        super().__init__()
        self.linear = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out
        

### *Lets create a dummy dataset*

In [3]:
features = torch.rand(10, 5)

## create a model
model = Model(num_features=features.shape[1])

## call the model
model(features)    ## internal the implement magic function so when create an object and auto cll forward function

tensor([[0.4814],
        [0.5833],
        [0.5012],
        [0.5223],
        [0.5836],
        [0.5375],
        [0.5722],
        [0.5772],
        [0.4510],
        [0.4652]], grad_fn=<SigmoidBackward0>)

### *to check the model weight*

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.1182,  0.2701, -0.4203,  0.3727,  0.0620]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([-0.0170], requires_grad=True)

### *to see the model info*

In [7]:
from torchinfo import summary
summary(model=model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## *Build one more model with hidden layer*

In [15]:
class Model(nn.Module):
    def __init__(self, input_features):
        super().__init__()
        self.linear = nn.Linear(in_features=input_features, out_features=3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(in_features=3, out_features=1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out

In [11]:
## crate the dataset into the GPU
device = torch.device('cuda')
my_data = torch.rand(10, 5, device=device)

In [16]:
model = Model(features.shape[1])
model(features)

tensor([[0.4532],
        [0.5092],
        [0.4499],
        [0.4676],
        [0.5022],
        [0.4593],
        [0.4994],
        [0.4552],
        [0.4657],
        [0.4693]], grad_fn=<SigmoidBackward0>)

In [17]:
## explore the model weight and bias
model.linear.weight

Parameter containing:
tensor([[ 0.3909,  0.3337,  0.2839,  0.3124,  0.3514],
        [-0.0062, -0.0218,  0.0066,  0.3487, -0.2288],
        [-0.1458, -0.3224, -0.0096, -0.0072,  0.2452]], requires_grad=True)

In [18]:
model.linear2.weight

Parameter containing:
tensor([[ 0.2432, -0.1672, -0.5075]], requires_grad=True)

In [19]:
model.linear.bias

Parameter containing:
tensor([-0.4380,  0.0778,  0.4462], requires_grad=True)

In [20]:
summary(model=model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## *More Robust The network use `sequential` container*

In [21]:
class Model(nn.Module):
    def __init__(self, input_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features=input_features, out_features=3),
            nn.ReLU(),
            nn.Linear(in_features=3, out_features=1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        
        return out

In [22]:
robust_model = Model(features.shape[1])
robust_model(features)

tensor([[0.4023],
        [0.3877],
        [0.3877],
        [0.3877],
        [0.3877],
        [0.3931],
        [0.3885],
        [0.3877],
        [0.3977],
        [0.3904]], grad_fn=<SigmoidBackward0>)